site_name: Transient
theme: readthedocs

nav:
    - Overview: index.md
    - Installation: installation.md
    - Command Line Interface:
      - 'create/run/start/stop': cli/run_create_start_stop.md
      - 'image': cli/image.md
      - 'cp': cli/cp.md
      - 'ps': cli/ps.md
      - 'rm': cli/rm.md
      - 'ssh': cli/ssh.md
      - 'commit': cli/commit.md
    - Disk Images:
      - 'Getting Existing Images': images/images.md
      - 'Building Images': images/building.md
      - 'Imagefile Format': images/format.md
    - Feature Details:
      - 'Using Shared Folders': details/shared-folders.md
