name: Transient

on: [push]

jobs:
  Check:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e '.[dev]'
    - name: Check Format
      run: |
        make check-format
    - name: Check Types
      run: |
        make check-types

  Test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Install package dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ssh qemu
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e '.[dev]'
    - name: Run tests
      run: |
        make test-ci